import React from 'react';
import './App.css';

import Navbar from './components/Navbar';
import Skills from './components/Skills';

function App() {
  return (
    <div className="App">
      <Navbar />
      <Skills />
      <div className="container">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget lobortis est, in lobortis ipsum. Vestibulum felis quam, blandit ut finibus ut, lobortis eget risus. Vestibulum vehicula dolor sed dignissim malesuada. Morbi a finibus diam. Maecenas sodales maximus lacus quis commodo. Praesent imperdiet tincidunt elit placerat finibus. Aenean fermentum turpis in volutpat facilisis. Nullam molestie mi in luctus semper. Sed vitae ultrices dui. Nulla malesuada metus ut elit finibus mattis. Integer maximus tristique velit, vel molestie enim posuere in. Mauris scelerisque ipsum lacus, a finibus magna auctor eu. Nullam consequat augue et augue viverra, nec luctus dolor sagittis. Quisque nec rutrum arcu, sit amet feugiat urna. Morbi vitae fringilla neque, eu consectetur leo. Mauris justo mauris, mollis nec aliquet eu, porta vitae mauris.
          Nullam non rhoncus ex. Quisque vel justo non dolor scelerisque dapibus sit amet quis nisi. Nam a faucibus justo. Mauris vel mauris porta, condimentum elit rutrum, faucibus sapien. Duis fringilla dui vitae magna pulvinar porta. Aenean vel luctus nunc, facilisis hendrerit ligula. Maecenas semper justo eget lorem vehicula, ut efficitur velit tempus.
          Nunc viverra ligula in felis scelerisque, ornare ullamcorper libero tristique. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur nec congue lorem. Suspendisse rhoncus nisl tempor nisl hendrerit lacinia. Aliquam cursus non libero eget interdum. Mauris ac ipsum consectetur, pharetra neque quis, mollis orci. Phasellus velit justo, pretium congue scelerisque vel, porta et mi. Phasellus sodales hendrerit lacus, non volutpat arcu vulputate sed. Aliquam molestie arcu turpis, sit amet condimentum mi rhoncus et. Donec eu efficitur neque. Sed interdum eleifend sapien nec iaculis.
          Maecenas eu faucibus justo. Integer volutpat dignissim massa, id condimentum leo fermentum ac. Integer fermentum fermentum malesuada. Donec in metus lorem. Curabitur malesuada bibendum libero, sit amet lacinia eros interdum nec. Suspendisse convallis massa ut vehicula aliquam. Morbi rhoncus, elit nec pharetra congue, sapien arcu sagittis leo, at ornare quam odio id urna. Nunc id lorem vitae libero dapibus sollicitudin. Nam a lacus est. Phasellus et convallis purus. Nulla ante neque, consectetur id sapien et, faucibus finibus sem. Etiam et risus interdum ipsum varius tristique. In vitae hendrerit lectus. Nullam ornare non tellus finibus gravida. Aenean laoreet sem nec orci ultricies maximus.
          Morbi sit amet nulla faucibus, porta urna et, pretium lacus. Cras ut dui tellus. Vestibulum fringilla dignissim ante, ut finibus libero. Nullam mi massa, aliquam non nibh ac, bibendum porttitor sapien. Duis non ex lacus. Pellentesque a nunc et neque vestibulum vulputate ac eu felis. Maecenas mollis malesuada est eget aliquet.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget lobortis est, in lobortis ipsum. Vestibulum felis quam, blandit ut finibus ut, lobortis eget risus. Vestibulum vehicula dolor sed dignissim malesuada. Morbi a finibus diam. Maecenas sodales maximus lacus quis commodo. Praesent imperdiet tincidunt elit placerat finibus. Aenean fermentum turpis in volutpat facilisis. Nullam molestie mi in luctus semper. Sed vitae ultrices dui. Nulla malesuada metus ut elit finibus mattis. Integer maximus tristique velit, vel molestie enim posuere in. Mauris scelerisque ipsum lacus, a finibus magna auctor eu. Nullam consequat augue et augue viverra, nec luctus dolor sagittis. Quisque nec rutrum arcu, sit amet feugiat urna. Morbi vitae fringilla neque, eu consectetur leo. Mauris justo mauris, mollis nec aliquet eu, porta vitae mauris.
          Nullam non rhoncus ex. Quisque vel justo non dolor scelerisque dapibus sit amet quis nisi. Nam a faucibus justo. Mauris vel mauris porta, condimentum elit rutrum, faucibus sapien. Duis fringilla dui vitae magna pulvinar porta. Aenean vel luctus nunc, facilisis hendrerit ligula. Maecenas semper justo eget lorem vehicula, ut efficitur velit tempus.
          Nunc viverra ligula in felis scelerisque, ornare ullamcorper libero tristique. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur nec congue lorem. Suspendisse rhoncus nisl tempor nisl hendrerit lacinia. Aliquam cursus non libero eget interdum. Mauris ac ipsum consectetur, pharetra neque quis, mollis orci. Phasellus velit justo, pretium congue scelerisque vel, porta et mi. Phasellus sodales hendrerit lacus, non volutpat arcu vulputate sed. Aliquam molestie arcu turpis, sit amet condimentum mi rhoncus et. Donec eu efficitur neque. Sed interdum eleifend sapien nec iaculis.
          Maecenas eu faucibus justo. Integer volutpat dignissim massa, id condimentum leo fermentum ac. Integer fermentum fermentum malesuada. Donec in metus lorem. Curabitur malesuada bibendum libero, sit amet lacinia eros interdum nec. Suspendisse convallis massa ut vehicula aliquam. Morbi rhoncus, elit nec pharetra congue, sapien arcu sagittis leo, at ornare quam odio id urna. Nunc id lorem vitae libero dapibus sollicitudin. Nam a lacus est. Phasellus et convallis purus. Nulla ante neque, consectetur id sapien et, faucibus finibus sem. Etiam et risus interdum ipsum varius tristique. In vitae hendrerit lectus. Nullam ornare non tellus finibus gravida. Aenean laoreet sem nec orci ultricies maximus.
          Morbi sit amet nulla faucibus, porta urna et, pretium lacus. Cras ut dui tellus. Vestibulum fringilla dignissim ante, ut finibus libero. Nullam mi massa, aliquam non nibh ac, bibendum porttitor sapien. Duis non ex lacus. Pellentesque a nunc et neque vestibulum vulputate ac eu felis. Maecenas mollis malesuada est eget aliquet.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget lobortis est, in lobortis ipsum. Vestibulum felis quam, blandit ut finibus ut, lobortis eget risus. Vestibulum vehicula dolor sed dignissim malesuada. Morbi a finibus diam. Maecenas sodales maximus lacus quis commodo. Praesent imperdiet tincidunt elit placerat finibus. Aenean fermentum turpis in volutpat facilisis. Nullam molestie mi in luctus semper. Sed vitae ultrices dui. Nulla malesuada metus ut elit finibus mattis. Integer maximus tristique velit, vel molestie enim posuere in. Mauris scelerisque ipsum lacus, a finibus magna auctor eu. Nullam consequat augue et augue viverra, nec luctus dolor sagittis. Quisque nec rutrum arcu, sit amet feugiat urna. Morbi vitae fringilla neque, eu consectetur leo. Mauris justo mauris, mollis nec aliquet eu, porta vitae mauris.
          Nullam non rhoncus ex. Quisque vel justo non dolor scelerisque dapibus sit amet quis nisi. Nam a faucibus justo. Mauris vel mauris porta, condimentum elit rutrum, faucibus sapien. Duis fringilla dui vitae magna pulvinar porta. Aenean vel luctus nunc, facilisis hendrerit ligula. Maecenas semper justo eget lorem vehicula, ut efficitur velit tempus.
          Nunc viverra ligula in felis scelerisque, ornare ullamcorper libero tristique. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur nec congue lorem. Suspendisse rhoncus nisl tempor nisl hendrerit lacinia. Aliquam cursus non libero eget interdum. Mauris ac ipsum consectetur, pharetra neque quis, mollis orci. Phasellus velit justo, pretium congue scelerisque vel, porta et mi. Phasellus sodales hendrerit lacus, non volutpat arcu vulputate sed. Aliquam molestie arcu turpis, sit amet condimentum mi rhoncus et. Donec eu efficitur neque. Sed interdum eleifend sapien nec iaculis.
          Maecenas eu faucibus justo. Integer volutpat dignissim massa, id condimentum leo fermentum ac. Integer fermentum fermentum malesuada. Donec in metus lorem. Curabitur malesuada bibendum libero, sit amet lacinia eros interdum nec. Suspendisse convallis massa ut vehicula aliquam. Morbi rhoncus, elit nec pharetra congue, sapien arcu sagittis leo, at ornare quam odio id urna. Nunc id lorem vitae libero dapibus sollicitudin. Nam a lacus est. Phasellus et convallis purus. Nulla ante neque, consectetur id sapien et, faucibus finibus sem. Etiam et risus interdum ipsum varius tristique. In vitae hendrerit lectus. Nullam ornare non tellus finibus gravida. Aenean laoreet sem nec orci ultricies maximus.
          Morbi sit amet nulla faucibus, porta urna et, pretium lacus. Cras ut dui tellus. Vestibulum fringilla dignissim ante, ut finibus libero. Nullam mi massa, aliquam non nibh ac, bibendum porttitor sapien. Duis non ex lacus. Pellentesque a nunc et neque vestibulum vulputate ac eu felis. Maecenas mollis malesuada est eget aliquet.
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget lobortis est, in lobortis ipsum. Vestibulum felis quam, blandit ut finibus ut, lobortis eget risus. Vestibulum vehicula dolor sed dignissim malesuada. Morbi a finibus diam. Maecenas sodales maximus lacus quis commodo. Praesent imperdiet tincidunt elit placerat finibus. Aenean fermentum turpis in volutpat facilisis. Nullam molestie mi in luctus semper. Sed vitae ultrices dui. Nulla malesuada metus ut elit finibus mattis. Integer maximus tristique velit, vel molestie enim posuere in. Mauris scelerisque ipsum lacus, a finibus magna auctor eu. Nullam consequat augue et augue viverra, nec luctus dolor sagittis. Quisque nec rutrum arcu, sit amet feugiat urna. Morbi vitae fringilla neque, eu consectetur leo. Mauris justo mauris, mollis nec aliquet eu, porta vitae mauris.
          Nullam non rhoncus ex. Quisque vel justo non dolor scelerisque dapibus sit amet quis nisi. Nam a faucibus justo. Mauris vel mauris porta, condimentum elit rutrum, faucibus sapien. Duis fringilla dui vitae magna pulvinar porta. Aenean vel luctus nunc, facilisis hendrerit ligula. Maecenas semper justo eget lorem vehicula, ut efficitur velit tempus.
          Nunc viverra ligula in felis scelerisque, ornare ullamcorper libero tristique. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur nec congue lorem. Suspendisse rhoncus nisl tempor nisl hendrerit lacinia. Aliquam cursus non libero eget interdum. Mauris ac ipsum consectetur, pharetra neque quis, mollis orci. Phasellus velit justo, pretium congue scelerisque vel, porta et mi. Phasellus sodales hendrerit lacus, non volutpat arcu vulputate sed. Aliquam molestie arcu turpis, sit amet condimentum mi rhoncus et. Donec eu efficitur neque. Sed interdum eleifend sapien nec iaculis.
          Maecenas eu faucibus justo. Integer volutpat dignissim massa, id condimentum leo fermentum ac. Integer fermentum fermentum malesuada. Donec in metus lorem. Curabitur malesuada bibendum libero, sit amet lacinia eros interdum nec. Suspendisse convallis massa ut vehicula aliquam. Morbi rhoncus, elit nec pharetra congue, sapien arcu sagittis leo, at ornare quam odio id urna. Nunc id lorem vitae libero dapibus sollicitudin. Nam a lacus est. Phasellus et convallis purus. Nulla ante neque, consectetur id sapien et, faucibus finibus sem. Etiam et risus interdum ipsum varius tristique. In vitae hendrerit lectus. Nullam ornare non tellus finibus gravida. Aenean laoreet sem nec orci ultricies maximus.
          Morbi sit amet nulla faucibus, porta urna et, pretium lacus. Cras ut dui tellus. Vestibulum fringilla dignissim ante, ut finibus libero. Nullam mi massa, aliquam non nibh ac, bibendum porttitor sapien. Duis non ex lacus. Pellentesque a nunc et neque vestibulum vulputate ac eu felis. Maecenas mollis malesuada est eget aliquet.
        </p>
      </div>
      <button id="btnScrollToTop">
        <span><i class="fa fa-chevron-up"></i></span>
      </button>
    </div>
  );
}

export default App;
